# Generated by Django 5.2.5 on 2025-08-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphinc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AddField(
            model_name='customuser',
            name='estado',
            field=models.CharField(choices=[('Habilitado', 'Habilitado'), ('Inhabilitado', 'Inhabilitado')], default='Habilitado', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Usuario', 'Usuario')], default='Usuario', max_length=20),
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='usuario',
        ),
    ]
