# Generated by Django 5.2.5 on 2025-08-25 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphinc', '0002_alter_customuser_options_customuser_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tallas', models.CharField(help_text="Tallas separadas por comas, e.g., 'S,M,L'", max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Accesorios', 'Accesorios')], default='Hombre', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
