# Generated by Django 5.2.5 on 2025-11-03 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphinc', '0007_categoria_imagen_producto_is_destacado_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemcarrito',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='talla',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='M', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='itemcarrito',
            unique_together={('carrito', 'producto', 'talla')},
        ),
        migrations.CreateModel(
            name='StockTalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=10)),
                ('stock', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apphinc.producto')),
            ],
            options={
                'unique_together': {('producto', 'talla')},
            },
        ),
    ]
