# Generated by Django 5.2.1 on 2025-11-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphinc', '0009_pedido_detallepedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktalla',
            name='stock_inicial',
            field=models.IntegerField(default=0),
        ),
    ]
