# Generated by Django 5.2.1 on 2025-11-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphinc', '0010_stocktalla_stock_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='email',
            field=models.EmailField(default='Admin@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_expiracion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta de Crédito/Débito'), ('paypal', 'PayPal'), ('transferencia', 'Transferencia Bancaria')], default='tarjeta', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nombre_completo',
            field=models.CharField(default='Admin', max_length=200),
        ),
        migrations.AddField(
            model_name='pedido',
            name='numero_tarjeta',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='ciudad',
            field=models.CharField(default='Ciudad no especificada', max_length=100),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='direccion_envio',
            field=models.TextField(default='Dirección no especificada'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('procesando', 'Procesando'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='telefono',
            field=models.CharField(default='0000000000', max_length=20),
        ),
    ]
