# Generated by Django 5.2.6 on 2025-11-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphinc', '0011_pedido_email_pedido_fecha_expiracion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='documento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telefono_personal',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
