# Generated by Django 5.2.6 on 2025-11-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphinc', '0012_customuser_documento_customuser_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallepedido',
            options={'verbose_name': 'Detalle de Pedido', 'verbose_name_plural': 'Detalles de Pedidos'},
        ),
        migrations.AlterField(
            model_name='pedido',
            name='email',
            field=models.EmailField(default='cliente@ejemplo.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nombre_completo',
            field=models.CharField(default='Cliente', max_length=200),
        ),
    ]
