# Generated by Django 5.2.1 on 2025-11-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphinc', '0014_movimientoinventario_registroventa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_expiracion',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='numero_tarjeta',
        ),
        migrations.AddField(
            model_name='pedido',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta de Crédito/Débito'), ('paypal', 'PayPal')], default='tarjeta', max_length=20),
        ),
    ]
